## Packages and Functions


We were previously using some simple functions such as print() and type() as well as the built in list functions. But these are maybe a bit simple for what we eventually want to do. We could build our own functions but for a lot of things that we want to do some clever person out there has probably done the work for us. But to access many of these we need to import what are called packages. Packages are essentially just a collection of functions that someone has compiled into one convenient "package". 

In [3]:
import numpy

To use a package we must first import that package. In reality we need to install the package first but this should have already been done for us for the packages we will need. 

To use the functions from a package we write import PACKAGENAME 

In [ ]:
numpy.pi

In [4]:
import numpy as np

We can also import a package under a different name. Normally this is just a shorter abbreviation to try and make coding faster. In this case we have called numpy as np.

In this case we are importing the package called numpy. This is a package that contains numerous (I mean literally hundreds, it is one of the largest and most commonly used packages) functions for use in data handling and mathematics. 

However the key part of of numpy is the numpy array. This is a powerful array structure that can be used in numerous data science applications.

In [7]:
a = np.array([1,2,3,4,5,6])

In [9]:
a

array([1, 2, 3, 4, 5, 6])

In [16]:
b = np.arange(10,30,5)

In [18]:
b

array([10, 15, 20, 25])

This function creates an array, between the first number and the second number with intervals of the third number

In [24]:
c = np.arange(1,11,1)

In [34]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Remember when creating numpy arrays you need to put regular brackets around the square brackets.

In [36]:
d = np.array[1,2,3,4]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [38]:
d = np.array([1,2,3,4])

In [39]:
d

array([1, 2, 3, 4])

Arrays can be multidimensional.

In [49]:
twoda = np.array([(1,2,3,4),(5,6,7,8)])

In [50]:
twoda

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

We're initialised an array with two dimensions in it, essentially two different lists of numbers in the same array. We can reference within this array.

In [52]:
twoda[0]

array([1, 2, 3, 4])

In [54]:
twoda[1]

array([5, 6, 7, 8])

And we can reference parts of that dimension.

In [62]:
twoda[0][0]

Here we've referenced the first value in the first dimension of the array. Initialise your own array and start altering and referencing parts within it.

It is important to understant what type of data our data is, if you remember our type() function checking things. With the array it is slightly different to check the type.

In [64]:
d.dtype

dtype('int32')

This has int in it so it is an integer type array.

In [66]:
f = np.array([1.1,2.2,3.3,4.4])

In [68]:
f 

array([ 1.1,  2.2,  3.3,  4.4])

In [70]:
f.dtype

dtype('float64')

This is a float type with decimal points.

We can do operations to arrays as well. They are incredbily powerful tools.

In [76]:
f + d

array([ 2.1,  4.2,  6.3,  8.4])

In [78]:
f * d

array([  1.1,   4.4,   9.9,  17.6])

In [80]:
a *2

array([ 2,  4,  6,  8, 10, 12])

The arrays however have to have the same dimensions or you need to specify the same dimensions using indexing

In [81]:
a + f

ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [84]:
a[0:4] + f

array([ 2.1,  4.2,  6.3,  8.4])

Inside the indexing : means a sequence between the two numbers so postion 0 to 4.

We can use some of the in built mathematical functions in numpy as well that let you perform various calculations.

In [31]:
np.e

2.718281828459045

In [33]:
np.sin(2)

0.90929742682568171

In [74]:
np.cos(2*np.pi)

1.0